// Quelle: docs/INHALTE.md §3 (Peter Pan).
import { defineProject } from '~/types/project'

export default defineProject({
  slug: 'peter-pan',
  title: 'Peter Pan',
  subtitle: { en: 'Adventure opera after J. M. Barrie · World premiere', de: 'Abenteueroper nach J. M. Barrie · Uraufführung' },
  venue: 'Philharmonie Luxembourg',
  year: 2024,
  pillar: 'direct',
  role: { en: 'Stage Director', de: 'Regie' },
  dates: {
    en: ['World premiere 4 May 2024, Philharmonie Luxembourg'],
    de: ['Uraufführung 4. Mai 2024, Philharmonie Luxembourg'],
  },
  tags: { en: ['Children’s opera', 'Adventure', 'World premiere'], de: ['Kinderoper', 'Abenteuer', 'Uraufführung'] },
  cover: {
    type: 'video',
    src: '/media/peter-pan/cover.mp4',
    poster: '/media/peter-pan/cover-poster.jpg',
    alt: {
      en: 'Peter Pan and Wendy talk on the wooden stage set, snow-covered fabric at their feet.',
      de: 'Peter Pan und Wendy im Gespräch auf der hölzernen Bühne, verschneiter Stoff zu ihren Füßen.',
    },
    width: 800,
    height: 1000,
    credit: 'Film: Philharmonie Luxembourg',
  },
  intro: {
    en: [
      'Frank Schwemmer’s new opera, with a libretto by Michael Frowin, takes J. M. Barrie’s adventure to Neverland and turns it into music theatre for young audiences: flight, pirates and the fear of growing up, told through voices and orchestra.',
      'The production was commissioned by the Philharmonie Luxembourg and had its world premiere there in 2024.',
    ],
    de: [
      'Frank Schwemmers neue Oper nach einem Libretto von Michael Frowin bringt J. M. Barries Abenteuer im Nimmerland als Musiktheater für junges Publikum auf die Bühne: Fliegen, Piraten und die Angst vorm Erwachsenwerden, erzählt mit Stimmen und Orchester.',
      'Die Auftragsproduktion der Philharmonie Luxembourg wurde dort 2024 uraufgeführt.',
    ],
  },
  gallery: [
    {
      type: 'single',
      label: { en: 'The worlds', de: 'Die Welten' },
      media: {
        type: 'image',
        src: '/media/peter-pan/01.jpg',
        alt: { en: 'Video projection: a watercolour forest with an autumn tree by the water.', de: 'Videoprojektion: ein Aquarell-Wald mit einem herbstlich gefärbten Baum am Wasser.' },
        width: 1638,
        height: 1024,
        credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
      },
    },
    {
      type: 'group-3',
      label: { en: 'Day and night', de: 'Tag und Nacht' },
      media: [
        {
          type: 'image',
          src: '/media/peter-pan/02a.jpg',
          alt: { en: 'Video projection: a golden sunset over water.', de: 'Videoprojektion: ein goldener Sonnenuntergang über dem Wasser.' },
          width: 819,
          height: 1024,
          credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
        },
        {
          type: 'image',
          src: '/media/peter-pan/02b.jpg',
          alt: { en: 'Video projection: a starry night sky over Neverland.', de: 'Videoprojektion: ein Sternenhimmel über Nimmerland.' },
          width: 819,
          height: 1024,
          credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
        },
        {
          type: 'image',
          src: '/media/peter-pan/02c.jpg',
          alt: { en: 'Video projection: pink and violet clouds at sunrise over the sea.', de: 'Videoprojektion: rosa und violette Wolken bei Sonnenaufgang über dem Meer.' },
          width: 819,
          height: 1024,
          credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
        },
      ],
    },
    {
      type: 'single',
      label: { en: 'The flight', de: 'Der Flug' },
      media: {
        type: 'image',
        src: '/media/peter-pan/03.jpg',
        alt: { en: 'Video projection: bright clouds seen from among the treetops.', de: 'Videoprojektion: helle Wolken, gesehen zwischen den Baumwipfeln.' },
        width: 1638,
        height: 1024,
        credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
      },
    },
    {
      type: 'group-3',
      label: { en: 'Cave, storm and ocean', de: 'Höhle, Sturm und Ozean' },
      media: [
        {
          type: 'image',
          src: '/media/peter-pan/04a.jpg',
          alt: { en: 'Video projection: the glowing exit of a blue-lit cave.', de: 'Videoprojektion: der leuchtende Ausgang einer blau schimmernden Höhle.' },
          width: 819,
          height: 1024,
          credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
        },
        {
          type: 'image',
          src: '/media/peter-pan/04b.jpg',
          alt: { en: 'Video projection: dark storm clouds with lightning.', de: 'Videoprojektion: dunkle Gewitterwolken mit einem Blitz.' },
          width: 819,
          height: 1024,
          credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
        },
        {
          type: 'image',
          src: '/media/peter-pan/04c.jpg',
          alt: { en: 'Video projection: a breaking wave on the open ocean.', de: 'Videoprojektion: eine brechende Welle auf offenem Meer.' },
          width: 819,
          height: 1024,
          credit: 'Video: Étienne Guiol, Thomas Ocampo, Johan Pirroux',
        },
      ],
    },
  ],
  videos: [{ provider: 'youtube', id: 'TRjf79QTV-s', title: 'Peter Pan' }],
  credits: [
    { role: { en: 'Music', de: 'Musik' }, name: 'Frank Schwemmer' },
    { role: { en: 'Libretto', de: 'Libretto' }, name: 'Michael Frowin' },
    { role: { en: 'Stage Director', de: 'Regie' }, name: 'Anisha Bondy' },
    { role: { en: 'Musical Director', de: 'Musikalische Leitung' }, name: 'Harry Ogg, David Fernández Caravaca' },
    { role: { en: 'Set', de: 'Bühne' }, name: 'Julia Hansen' },
    { role: { en: 'Costumes', de: 'Kostüme' }, name: 'Uta Jäger' },
    { role: { en: 'Lighting', de: 'Licht' }, name: 'Michael Morgan' },
    { role: { en: 'Video', de: 'Video' }, name: 'Étienne Guiol, Thomas Ocampo, Johan Pirroux' },
    { role: { en: 'Orchestra', de: 'Orchester' }, name: 'Luxembourg Philharmonic' },
    { role: { en: 'Choir', de: 'Chor' }, name: 'Pueri Cantores du Conservatoire de la Ville de Luxembourg · Pierre Nimax' },
    {
      role: { en: 'Cast', de: 'Mit' },
      name: 'Peter Kirk, Georgina Fürstenberg, Juliana Zara, Maria Fiselier, Beniamin Pop, William Wallace',
    },
  ],
  awards: [],
  press: [],
  featured: true,
  order: 5,
})
